### ISSUE TITLE
undefined method `first' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ChiefVitor** [fatbeard2/FUT17-autobuyer#2]
ruby ./buy.rb 180819 3000 4000
./buy.rb:106:in `block in <main>': undefined method `first' for nil:NilClass (NoMethodError)
	from ./buy.rb:104:in `loop'
	from ./buy.rb:104:in `<main>'

http://i.imgur.com/mXIh2iO.png

**Comment by fatbeard2** [comment]
I've updated script. Its probably because of wrong session_id or token

**Comment by fatbeard2** [comment]
Btw, I'm also farming with lallana, so you might consider pick another player, so we won't interfere with each other :)

**Comment by ChiefVitor** [comment]
Ok bruh

**Comment by ChiefVitor** [comment]
I will try it now :)

**Comment by ChiefVitor** [comment]
Unexpected response while fetching auctions
{"reason"=>"expired session", "message"=>nil, "code"=>401}

I put everything right, and the api keeps telling expired session

**Comment by ChiefVitor** [comment]
Are you talking about this right ?

POST /ut/game/fifa17/trade/status?tradeIds=173862687530%2C173862700171%2C173870315773%2C173870315782%2C173870315784%2C173870315786%2C173870315788%2C173870315794%2C173870315795%2C173870315796%2C173870318952%2C173870318972%2C173870318975%2C173870315798%2C173870318974 HTTP/1.1
Host: utas.external.s2.fut.ea.com
Connection: keep-alive
Content-Length: 1
Origin: https://www.easports.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Content-Type: application/json
Accept: application/json
X-UT-SID: 0e6b9a29-1251-4ab6-89b7-6e9684713cc3
X-Requested-With: ShockwaveFlash/23.0.0.185
X-UT-Embed-Error: true
X-UT-PHISHING-TOKEN: 6016120839313187537
X-HTTP-Method-Override: GET
Referer: https://www.easports.com/iframe/fut17/bundles/futweb/web/flash/FifaUltimateTeam.swf?cl=163759
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: ce_sv_tra=true; optimizelyEndUserId=oeu1476308094280r0.7922070290401919; optimizelySegments=%7B%222152681518%22%3A%22none%22%2C%222164421345%22%3A%22direct%22%2C%222172201290%22%3A%22gc%22%2C%222177130812%22%3A%22false%22%7D; optimizelyBuckets=%7B%7D; _ga=GA1.2.771188350.1476308096; utag_main=v_id:015786ea5048006ba7c3107d826005072012c06a0086e$_sn:4$_ss:0$_st:1476393435166$_pn:12%3Bexp-session$ses_id:1476390966052%3Bexp-session; _nx_mpcid=425376ad-e4fc-4c79-98b7-5b5a1a20b96a

**Comment by fatbeard2** [comment]
oh, I think I got it. What platform are you playing on? I'm on xbox one. I think other platforms have different urls.

**Comment by ChiefVitor** [comment]
Im on PS4

**Comment by fatbeard2** [comment]
Yeah. You have `https://utas.external.s2.fut.ea.com` and in file its `utas.external.s3.fut.ea.com` 
You can just change it everywhere. Maybe I'll fix it later

**Comment by ChiefVitor** [comment]
Yeah, im doing it

**Comment by ChiefVitor** [comment]
Fixed! S2 for ps4
http://i.imgur.com/tg2Sktg.png

**Comment by fatbeard2** [comment]
congrats!

**Comment by ChiefVitor** [comment]
How much are you sniping Lallana and how much you selling

**Comment by fatbeard2** [comment]
Sniping for 3000 selling for 3400

**Comment by fatbeard2** [comment]
But it looks like that its getting cheaper as it gets closer to the night

**Comment by ChiefVitor** [comment]
Yes men

**Comment by ChiefVitor** [comment]
Bruh if your bot gets to much people probably we will get ban ;) Make sure you dont make it so easier to work
