### ISSUE TITLE
Session expired

### ISSUE THREAD

**Issue by JeremyLotito** [fatbeard2/FUT17-autobuyer#7]
Hi,

thx for your work.
However, i always have the error message "Session expired" when i run the command. 
Is it normal ? I am doing something wrong ?

Thx

**Comment by fatbeard2** [comment]
Hi. Its probably because of this issue. https://github.com/fatbeard2/FUT17-autobuyer/issues/2

**Comment by JeremyLotito** [comment]
TY i changed URL's and it works !!
